apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gtw-prod-6
  namespace: ns-infra
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      hostname: "myapp.com"
      protocol: HTTP
      port: 8080
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gtw-prod-6: "true"