apiVersion: v1
kind: Namespace
metadata:
  name: ns-infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-shield
  labels:
    gtw-prod-6: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-hydra
  labels:
    gtw-prod-6: "true"
