apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gtw-prod-1
spec:
  gatewayClassName: nginx
  listeners:
  - name: list-safc
    protocol: HTTP
    port: 8080
    allowedRoutes:
      namespaces:
        from: Same

